---
title: Laena's minima test
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author:
  name: Laena Ilk
  email: laena.ilk@door3.com
description: This is a test site for Laena to figure out siteleaf, jekyll, github
  pages, and making the site multi-lingual.
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
header_pages:
- about.md
minima:
  skin: classic
